version: '2'
services:
    streamerdemo-app:
        image: streamerdemo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://streamerdemo-postgresql:5432/streamerdemo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    streamerdemo-postgresql:
        extends:
            file: postgresql.yml
            service: streamerdemo-postgresql
